#include "types.h"
#include <SDL.h>
#include <stdlib.h>

typedef SDL_Surface* HBITMAP;

int initWindows(void);
void assertFailed(const char* srcFilename, int lineNumber);
int showErrorMessage(LPCSTR text);
BOOL allocateMemory(void);
BOOL loadSoundFunc(void);
BOOL loadSound(uint32_t resourceId, Sound* sound);
void statusWindowFindLongestTextString(HDC hdc, int32_t* maxLength, LPCSTR textStr, int textLength);
void paintStatusWindow(HWND hWnd);
BOOL calculateStatusWindowDimensions(HWND hWnd);
void statusWindowReleaseDC(HWND hWnd);
// LRESULT CALLBACK skiMainWndProc(HWND hWnd, uint32_t message, WPARAM wParam, LPARAM lParam);
// LRESULT CALLBACK skiStatusWndProc(HWND hWnd, uint32_t message, WPARAM wParam, LPARAM lParam);
void paintActors(HDC hdc, RECT* paintRect);
void pauseGame(void);
void togglePausedState(void);
void freeSoundResource(Sound* sound);
void cleanupSound(void);
void playSound(int num);
Actor* addActor(Actor* actor, BOOL insertBack);
HBITMAP loadBitmapResource(uint32_t resourceId);
BOOL loadBitmaps(HWND hWnd);
void handleWindowMoveMessage(HWND hWnd);
void updateWindowsActiveStatus(void);
void setPointerToNull(PermObjectList* param_1);
Actor* getFreeActor(void);
BOOL setupGame(void);
int32_t ski_random(int32_t maxValue);
Actor* updateActorPositionWithVelocityMaybe(Actor* actor);
Actor* addActorOfTypeWithSpriteIdx(int actorType, uint32_t spriteIdx);
void actorSetFlag8IfFlag1IsUnset(Actor* actor);
void removeFlag8ActorsFromList(void);
BOOL changeScratchBitmapSize(int32_t newWidth, int32_t newHeight);
void actorClearFlag10(Actor* actor1, Actor* actor2);
Actor* setActorFrameNo(Actor* actor, uint32_t frameNo);
Actor* actorSetSpriteIdx(Actor* actor, uint32_t spriteIdx);
Actor* duplicateAndLinkActor(Actor* actor);
void updateActorRectsAfterPlayerMove(int32_t newPlayerX, int32_t newPlayerY);
void getRandomOffscreenStartingPosition(int borderType, int32_t* xPos, int32_t* yPos);
int randomActorType1(void);
int randomActorType2(void);
int randomActorType3(void);
int areaBasedActorType(void);
Actor* updateActorType1_Beginner(Actor* actor);
Actor* updateActorType2_dog(Actor* actor);
Actor* updateActorType9_treeOnFire(Actor* actor);
Actor* updateActor(Actor* actor);
Actor* updatePlayerActor(Actor* actor);
void updateSsGameMode(Actor* actor, int32_t xPos, int32_t yPos);
int FUN_00402e30(int param_1, int param_2, int param_3, int param_4, int param_5);
void resetPlayerFrameNo(void);
void updateFsGameMode(Actor* actor, int32_t xPos, int32_t yPos);
void updateGsGameMode(Actor* actor, int32_t xPos, int32_t yPos);
Actor* updateActorTypeA_walkingTree(Actor* actor);
Actor* updateActorType3_snowboarder(Actor* actor);
Actor* handleActorCollision(Actor* actor1, Actor* actor2);
Actor* addActorForPermObject(PermObject* permObject);
void updatePermObjectActorType4(PermObject* permObject);
void updateYeti(PermObject* permObject);
void FUN_004046e0(PermObjectList* permObjList);
void deleteWindowObjects(void);
void handleMouseClick(void);
int getSkierGroundSpriteFromMousePosition(int32_t param_1, int32_t param_2);
int getSkierInAirSpriteFromMousePosition(int32_t param_1, int32_t param_2);
void handleMouseMoveMessage(int32_t xPos, int32_t yPos);
void updateActorsAfterWindowResize(int32_t centreX, int32_t centreY);
void updateRectForSpriteAtLocation(RECT* rect, Sprite* sprite, int32_t newX, int32_t newY, int32_t param_5);
void formatAndPrintStatusStrings(HDC windowDC);
int resetGame(void);
void updatePermObject(PermObject* permObject);
Actor* updateActorPositionMaybe(Actor* actor, int32_t newX, int32_t newY, int32_t inAir);
void updateWindowSize(HWND hWnd);
Actor* updateActorVelMaybe(Actor* actor, const ActorVelStruct* param_2);
PermObject* addPermObject(PermObjectList* objList, PermObject* permObject);
void setupPermObjects(void);
//void handleKeydownMessage(SDL_Event* e);
void handleKeydownMessage();
void updateGameState(void);
BOOL createBitmapSheets(HDC param_1);
void drawWindow(HDC hdc, RECT* rect);
void drawActor(HDC hdc, Actor* actor);
void updateEntPackIniKeyValue(LPCSTR configKey, int value, int isTime);
void permObjectSetSpriteIdx(PermObject* permObject, uint32_t spriteIdx);
void mainWindowPaint(HWND param_1);

void HandleWindowMessage(SDL_Event* e);

void timerUpdateFunc(void);
